### ISSUE TITLE
Interaction terms cause undefined column selections

### ISSUE THREAD

**Issue by rymc9384** [benjaminschlegel/brant#1]
Running the test on a model that contains interaction terms in the formula results in an error, as the interaction "variables" cannot be found in the dataframe. Building in functionality to handle interaction terms would be very helpful. A minimal reproducible example based on the vignette is provided below.

    data = MASS::survey 
    data$Smoke = ordered(MASS::survey$Smoke,levels=c("Never","Occas","Regul","Heavy")) 
    model1 = MASS::polr(Smoke ~ Sex*Height, data=data, Hess=TRUE) 
    summary(model1) 
    brant(model1) 

The error is raised regardless of whether the interaction contains a factor or not (e.g., if ``sex`` was coded 0-1 in the above example). Thanks and cheers.

**Comment by benjaminschlegel** [comment]
The issue is known since a while, I just did not find time to improve the function to handle also interactions.

**Comment by rymc9384** [comment]
No worries! Just wanted to let you know in case it hadn't come up yet.

**Comment by benjaminschlegel** [comment]
I updated the package on Github now that it works with interactions. Please let me know if you still find a situation that causes an error.
