### ISSUE TITLE
The brant() does not work with model with log()

### ISSUE THREAD

**Issue by nickhkor** [benjaminschlegel/brant#2]
Thanks Benjamin for creating the brant package. It is useful.

Similar to the issue of interaction in regression, I found that including a log transformation in the model would also cause an error. However, if we create a column 

A minimal example here:
```
data = MASS::survey 
data$Smoke = ordered(MASS::survey$Smoke,levels=c("Never","Occas","Regul","Heavy")) 
model1 = MASS::polr(Smoke ~ Sex + log(Height), data=data, Hess=TRUE) 
summary(model1) 
brant(model1) 
```

However, if the variable is transformed and created in a dataframe, it works well.
```
data$ln_Height = log(data$Height)
model2 = MASS::polr(Smoke ~ Sex + ln_Height, data=data, Hess=TRUE) 
summary(model2) 
brant(model2) 
```

**Comment by benjaminschlegel** [comment]
I uploaded a new developer version of the package on GitHub. It should know work with log(), poly(), I(^2) and similar things. Interactions still do not work. Please tell me if you still get error messages with any model which do not include interactions.
