### ISSUE TITLE
Negative Chi Square

### ISSUE THREAD

**Issue by AGallyer** [benjaminschlegel/brant#3]
Hello,

I ran the following and received a negative chi-square for the omnibus and one of my predictors:

`aq.intent.ord <- polr(as.factor(SBQR4) ~ military_years + AQ_Total + unit_cohesion_total, data = data_complete, Hess = TRUE)

brant(aq.intent.ord)`

Which resulted in the Omnibus and one of my predictors having the following:

Omnibus              -4.681544 15   1.0000000
military_years      -13.528010  5   1.0000000

Can I assume that the absolute value of the X2 is the correct test statistic?

**Comment by benjaminschlegel** [comment]
I am not sure. Can you provide an example which I can replicate?

**Comment by benjaminschlegel** [comment]
The brant test can in rare cases lead to negative Chi2 values. This also happens in Stata. Then the test is just no valid.

**Comment by AGallyer** [comment]
You can probably disregard now, I no longer work for the organization with the data and I wouldn't have been able to share the data anyway. Thank you and I will make sure to try and include a reproducible example in the future.
