### ISSUE TITLE
brant no longer working after installation on Feb 1 2024

### ISSUE THREAD

**Issue by amacbale** [benjaminschlegel/brant#7]
Hi there,

I was using the `brant.test` function yesterday over some ordinal logit models on a different machine. When I installed the package on my home PC and reran my code, I found that `brant.test` is now just `brant` and it seems suddenly unable to handle factor variables. When R automatically appends factor levels to the variable name in the model specification, `brant` cannot find the variable.

**Comment by benjaminschlegel** [comment]
Hi, it was always called brant and never brant.test. It should be able to handle factor variables, I used it a lot with them. Can you send me a reproducable example which does not work that I can test it?

**Comment by amacbale** [comment]
That is very alarming! I was certainly running a function called brant.test... I am working on creating a reproducible example. Thank you for your prompt response!

**Comment by amacbale** [comment]
I'm at a loss. I cannot reproduce the error when I use simulated data. This code below produces a dataset similar in structure to what I'm working with and calls brant without error. You'll below that my models are specified exactly the same. (apologies for the formatting. I tried to put code in code blocks and my comments as text, but I'm not used to posting on GitHub... Sorry!)
 ```set.seed(123) 
n <- 163
df_fake <- data.frame(
  DV1_FreqVideoClass = factor(sample(c("Never", "Rarely", "Sometimes", "Often"), n, replace = TRUE), 
                              levels = c("Never", "Rarely", "Sometimes", "Often"), ordered = TRUE),
  IV1_L2 = factor(sample(0:1, n, replace = TRUE)),
  IV2_YearsTeaching = round(runif(n, min = 0, max = 30)),
  IV3_TechInClass = factor(sample(c("No","Yes"), n, replace = TRUE)),
  IV5_VideosImportant = factor(sample(c("No","Unsure","Yes"), n, replace = TRUE)),
  IV9_ComfortVideo = factor(sample(c("Uncomfortable", "Slightly Uncomfortable", "Comfortable", "Very Comfortable"), n, replace = TRUE),
                            levels = c("Uncomfortable", "Slightly Uncomfortable", "Comfortable", "Very Comfortable"), ordered = TRUE)
)
str(df_fake)

testmodel <- polr(mod1, data = df_fake)
brant(testmodel)```

A summary of this model output looks like this:

```summary(testmodel)

Re-fitting to get Hessian

Call:
polr(formula = mod1, data = df_fake)

Coefficients:
                             Value Std. Error t value
IV2_YearsTeaching         -0.01133    0.01717 -0.6600
IV1_L21                   -0.07572    0.29070 -0.2605
IV3_TechInClassYes         0.16489    0.29218  0.5643
IV5_VideosImportantUnsure  0.07409    0.36316  0.2040
IV5_VideosImportantYes    -0.50673    0.36898 -1.3733
IV9_ComfortVideo.L         0.56920    0.30725  1.8525
IV9_ComfortVideo.Q        -0.20448    0.29870 -0.6846
IV9_ComfortVideo.C         0.08205    0.27581  0.2975

Intercepts:
                 Value   Std. Error t value
Never|Rarely     -1.4442  0.4078    -3.5418
Rarely|Sometimes -0.0891  0.3895    -0.2287
Sometimes|Often   1.3127  0.4093     3.2076

Residual Deviance: 437.7818 
AIC: 459.7818 ```

And a summary of my actual model output looks like this:

```models$DV1_FreqVideoClass %>% summary()
Call:
polr(formula = model, data = df, Hess = TRUE)

Coefficients:
                               Value Std. Error  t value
IV2_YearsTeaching          0.0007049    0.01754  0.04019
IV1_L21                   -0.4108756    0.34611 -1.18712
IV3_TechInClassYes         0.2988742    0.47567  0.62832
IV5_VideosImportantUnsure -1.4033694    1.41475 -0.99196
IV5_VideosImportantYes     0.4272213    1.35746  0.31472
IV9_ComfortVideo.L         3.0709215    0.73869  4.15725
IV9_ComfortVideo.Q        -0.2133886    0.56680 -0.37648
IV9_ComfortVideo.C        -0.1879933    0.42562 -0.44169

Intercepts:
                     Value   Std. Error t value
Never|Rarely         -2.3534  1.3826    -1.7021
Rarely|Sometimes     -0.7460  1.3622    -0.5476
Sometimes|Very often  1.9631  1.3656     1.4375

Residual Deviance: 307.9429 
AIC: 329.9429 ```

When I run brant on my actual model above, I receive this error:
`brant(models$DV1_FreqVideoClass)
Error in eval(predvars, data, env) : object 'IV3_TechInClass' not found`

I'm at a loss! Everything was working just a day ago!

**Comment by benjaminschlegel** [comment]
Its hard to tell if I cannot run it on my machine. You can also send me your R code and data per e-mail if you do not want to put it online (--> kontakt@benjaminschlegel.ch).

**Comment by amacbale** [comment]
That would be very appreciated! I'll send you an email with a permuted data set.

**Comment by amacbale** [comment]
Hello. Any update on this?

**Comment by benjaminschlegel** [comment]
I checked it now. The line m_model <- eval.parent(m_model) in the function causes an error because of infinite recursion in C (no idea why). If you specifiy the models directly with the formula (like: models[[1]] = polr(DV1_FreqVideoClass ~ IV2_YearsTeaching + IV1_L2 + IV3_TechInClass + IV5_VideosImportant + IV9_ComfortVideo, data = permuted_df, Hess = TRUE)) then it works as expected.

**Comment by amacbale** [comment]
Very bizarre. You're right, manually creating the model objects inside the call to polr works, but creating the formula object with as.formula breaks it. Thank you for looking into this!

Also, fyi, I found the function I was talking about before... I was using brant.test from the gofcat package. I'd google for brant.test and literally find no mention of it so I was baffled.
